// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sedna.Service.Requirements.API.Data;

namespace Sedna.Service.Requirements.API.Migrations
{
    [DbContext(typeof(RequirementsDbContext))]
    [Migration("20200407162459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.requirement_context_requirement_context_id_seq", "'requirement_context_requirement_context_id_seq', '', '1', '1', '', '', 'Int64', 'False'");

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Context", b =>
                {
                    b.Property<int>("ContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("context_id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('context_context_seq'::regclass)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasColumnName("reference_key")
                        .HasColumnType("character varying(75)")
                        .HasComment(@"A human-readable unique key for each record
to simplify coding.  More understandable
than the ID but less change-able than the
Description field. ")
                        .HasMaxLength(75);

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnName("tag")
                        .HasColumnType("text");

                    b.HasKey("ContextId");

                    b.HasIndex("ContextId")
                        .IsUnique()
                        .HasName("context_context_uindex");

                    b.HasIndex("ReferenceKey")
                        .IsUnique()
                        .HasName("context_reference_tag_uindex");

                    b.ToTable("context");

                    b.HasComment(@"The Brighton Cromwell workflow steps and contexts 
in which requirements might be relevant or impact 
activity/decisions/etc.  For example, ""PreAward.Rfq.Creation""
and ""PostAward.PurchaseOrder.Creation.""");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Requirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("requirement_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_ts")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_user_id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("529");

                    b.Property<bool>("IsActive")
                        .HasColumnName("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredPhrasing")
                        .HasColumnName("preferred_phrasing")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewDt")
                        .HasColumnName("review_dt")
                        .HasColumnType("date");

                    b.Property<int?>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("integer");

                    b.Property<string>("SourceText")
                        .HasColumnName("source_text")
                        .HasColumnType("text");

                    b.Property<string>("SourceTextLocation")
                        .HasColumnName("source_text_location")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnName("subject_id")
                        .HasColumnType("integer")
                        .HasComment(@"The external ID of the thing that this requirement pertains to.  e.g., the opportunity_id, or opportunity_line_id, etc.  
Note that this database does not keep a list of these, nor know what such entities are.
The calling service needs to know what it's looking for based on its own data and organization.");

                    b.Property<int?>("TopicId")
                        .HasColumnName("topic_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_ts")
                        .HasColumnType("timestamp(3) without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UpdatedUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_user_id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("529");

                    b.HasKey("RequirementId");

                    b.HasIndex("RequirementId")
                        .HasName("requirement_requirement_id_index");

                    b.HasIndex("SourceId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TopicId");

                    b.ToTable("requirement");

                    b.HasComment(@"The specifics of a given requirement, including 
what it pertains to (a given Opportunity or Line), 
the source it came from (e.g., a DIBBS solicitation 
PDF), what the original source of the requirement said
and what re-phrasing we want to use instead for clarity.	");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.RequirementContext", b =>
                {
                    b.Property<int>("RequirementContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("requirement_context_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContextId")
                        .HasColumnName("context_id")
                        .HasColumnType("integer");

                    b.Property<int>("RequirementId")
                        .HasColumnName("requirement_id")
                        .HasColumnType("integer");

                    b.HasKey("RequirementContextId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("ContextId", "RequirementId")
                        .IsUnique()
                        .HasName("requirement_context_context_id_requirement_id_uindex");

                    b.ToTable("requirement_context");

                    b.HasComment(@"List of the circumstances or contexts in which 
a particular requirement is meaningful or relevant.  
For instance, certain packaging requirements can
affect pricing, so ""PreAward.Bid.Creation"" would be a
relevant context, as would ""Warehouse.Packaging.Alert.""");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Source", b =>
                {
                    b.Property<int>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("source_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnName("external_identifier")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying");

                    b.Property<int?>("SourceTypeId")
                        .HasColumnName("source_type_id")
                        .HasColumnType("integer");

                    b.HasKey("SourceId");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique()
                        .HasName("source_external_identifier_uindex");

                    b.HasIndex("SourceTypeId");

                    b.ToTable("source");

                    b.HasComment(@"The source of the requirement.  This can be 
a specific solicitation PDF, a Word document,
an Excel file, or a person.");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.SourceType", b =>
                {
                    b.Property<int>("SourceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("source_type_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasColumnName("reference_key")
                        .HasColumnType("text")
                        .HasComment(@"A human-readable unique key for each record
to simplify coding.  More understandable
than the ID but less change-able than the
Name field. ");

                    b.HasKey("SourceTypeId");

                    b.HasIndex("ReferenceKey")
                        .IsUnique()
                        .HasName("source_type_reference_key_uindex");

                    b.ToTable("source_type");

                    b.HasComment("Different source types, like PDF, URL, a Sedna User, or other.");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("subject_id")
                        .HasColumnType("integer")
                        .HasComment("The autoincremented id for the record")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("description")
                        .HasColumnType("text")
                        .HasDefaultValueSql("''::text")
                        .HasComment("A human-readable description, for UI display.  For example \"NSN ##### (Oil Filter)\"");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnName("external_identifier")
                        .HasColumnType("text")
                        .HasComment("The external id that the calling routine knows this subject by. For an Opportunity, likely the \"opportunity_id\"; for an Opportunity Line, the \"opportunity_line_id.\"");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnName("subject_type_id")
                        .HasColumnType("integer")
                        .HasComment("The type of entity this is; an Opportunity, an Opportunity Line, etc.");

                    b.Property<string>("Tag")
                        .HasColumnName("tag")
                        .HasColumnType("json")
                        .HasComment("An optional field that permits descriptions of the entity, in key-value pairs.");

                    b.HasKey("SubjectId");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique()
                        .HasName("subject_external_identifier_uindex");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasName("subject_subject_id_uindex");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("subject");

                    b.HasComment(@"The ""subject"" of the requirement; what it 
pertains to.  The Opportunity, the 
Opportunity Line, the Award or Award 
Line, etc.");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.SubjectType", b =>
                {
                    b.Property<int>("SubjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("subject_type_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying");

                    b.Property<string>("ReferenceKey")
                        .HasColumnName("reference_key")
                        .HasColumnType("text")
                        .HasComment(@"A human-readable unique key for each record
to simplify coding.  More understandable
than the ID but less change-able than the
Name field. ");

                    b.HasKey("SubjectTypeId");

                    b.ToTable("subject_type");

                    b.HasComment(@"Things we can attach requirements to: 
Opportunities, Opp Lines, Awards, Award 
Lines, Vendors, Customers, Parts, 
Vendor-Parts, etc.");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.SubjectTypeTopic", b =>
                {
                    b.Property<int>("SubjectTypeTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("subject_type_topic_id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('entity_concept_entity_concept_id_seq'::regclass)");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnName("subject_type_id")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnName("topic_id")
                        .HasColumnType("integer");

                    b.HasKey("SubjectTypeTopicId");

                    b.HasIndex("SubjectTypeId");

                    b.HasIndex("SubjectTypeTopicId")
                        .IsUnique()
                        .HasName("subject_type_topic_subject_topic_id_uindex");

                    b.HasIndex("TopicId");

                    b.ToTable("subject_type_topic");

                    b.HasComment(@"A cross reference of the topics that are 
pertinent to each entity type.  For instance, 
an Opportunity can have requirements around 
""DeliveryDate"" while an OpportunityLine 
can have them about ""ShelfLife.""");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("topic_id")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('concept_concept_id_seq'::regclass)");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying");

                    b.Property<string>("PreferredPhrasing")
                        .HasColumnName("preferred_phrasing")
                        .HasColumnType("text")
                        .HasComment("The desired paraphrasing/layman's terminloogy for this concept (e.g., \"Vendor will not use Child Labor\")");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasColumnName("reference_key")
                        .HasColumnType("text")
                        .HasComment(@"A human-readable unique key for each record
to simplify coding.  More understandable
than the ID but less change-able than the
Name field. ");

                    b.HasKey("TopicId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("topic_name_uindex");

                    b.ToTable("topic");

                    b.HasComment(@"The overarching concept the requirement is 
in service to; e.g., ""Shelf Life,"" 
""Mercury"", ""Hazmat""");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.TopicContext", b =>
                {
                    b.Property<int>("TopicContextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("topic_context_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContextId")
                        .HasColumnName("context_id")
                        .HasColumnType("integer");

                    b.Property<int>("TopicId")
                        .HasColumnName("topic_id")
                        .HasColumnType("integer");

                    b.HasKey("TopicContextId");

                    b.HasIndex("ContextId");

                    b.HasIndex("TopicContextId")
                        .IsUnique()
                        .HasName("topic_context_topic_context_id_uindex");

                    b.HasIndex("TopicId");

                    b.ToTable("topic_context");

                    b.HasComment(@"Cross-reference of the contexts that are 
typically impacted by requirements associated 
with each topic.  These provide a templated 
pattern of default contexts when adding new 
requirements for that topic.");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.TopicSearch", b =>
                {
                    b.Property<int>("TopicSearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("topic_search_id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsWholeWord")
                        .HasColumnName("is_whole_word")
                        .HasColumnType("boolean")
                        .HasComment(@"If true, this string will be searched as a whole word. 
Best for short terms or acronyms that might appear inside
other words, such as First Article Test abbreviated
to ""FAT"" might appear inside ""fatuous"" or ""infatuated""
or ""indefatiguable.""  Though if those words start to
appear in DIBBS solicitations, someone at DLA is dearly
in need of a vacation or counseling or both.");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasColumnName("search_string")
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnName("topic_id")
                        .HasColumnType("integer");

                    b.HasKey("TopicSearchId");

                    b.HasIndex("TopicId");

                    b.ToTable("topic_search");

                    b.HasComment(@"The various search strings used to detect 
a requirement in a source PDF/webpage/etc. 
(e.g., ""Shelf life"" vs. ""shelflife"" vs. 
""shelf-life"")");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Requirement", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.Source", "Source")
                        .WithMany("Requirement")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("requirement_source_source_id_fk");

                    b.HasOne("Sedna.Service.Requirements.API.Data.Subject", "Subject")
                        .WithMany("Requirement")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("requirement_subject_subject_id_fk")
                        .IsRequired();

                    b.HasOne("Sedna.Service.Requirements.API.Data.Topic", "Topic")
                        .WithMany("Requirement")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("requirement_topic_topic_id_fk");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.RequirementContext", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.Context", "Context")
                        .WithMany("RequirementContext")
                        .HasForeignKey("ContextId")
                        .HasConstraintName("requirement_context_context_context_fk")
                        .IsRequired();

                    b.HasOne("Sedna.Service.Requirements.API.Data.Requirement", "Requirement")
                        .WithMany("RequirementContext")
                        .HasForeignKey("RequirementId")
                        .HasConstraintName("requirement_context_requirement_requirement_id_fk")
                        .IsRequired();
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Source", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.SourceType", "SourceType")
                        .WithMany("Source")
                        .HasForeignKey("SourceTypeId")
                        .HasConstraintName("source_source_type_source_type_id_fk");
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.Subject", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.SubjectType", "SubjectType")
                        .WithMany("Subject")
                        .HasForeignKey("SubjectTypeId")
                        .HasConstraintName("subject_entity_type_entity_type_id_fk")
                        .IsRequired();
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.SubjectTypeTopic", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.SubjectType", "SubjectType")
                        .WithMany("SubjectTypeTopic")
                        .HasForeignKey("SubjectTypeId")
                        .HasConstraintName("subject_topic_subject_subject_id_fk")
                        .IsRequired();

                    b.HasOne("Sedna.Service.Requirements.API.Data.Topic", "Topic")
                        .WithMany("SubjectTypeTopic")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("subject_topic_topic_id_fk")
                        .IsRequired();
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.TopicContext", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.Context", "Context")
                        .WithMany("TopicContext")
                        .HasForeignKey("ContextId")
                        .HasConstraintName("topic_context_context_context_fk")
                        .IsRequired();

                    b.HasOne("Sedna.Service.Requirements.API.Data.Topic", "Topic")
                        .WithMany("TopicContext")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("topic_context_topic_topic_id_fk")
                        .IsRequired();
                });

            modelBuilder.Entity("Sedna.Service.Requirements.API.Data.TopicSearch", b =>
                {
                    b.HasOne("Sedna.Service.Requirements.API.Data.Topic", "Topic")
                        .WithMany("TopicSearch")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("topic_search_topic_topic_id_fk")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
